app:
    resource: "@Ecommerce/Controller/"
    type:     annotation

#***************************************************************************
# INDEX CONTROLLER
#***************************************************************************

home:
    path:		/
    defaults:	{ _controller: Ecommerce:Index:index }

#***************************************************************************
# ACCOUNT CONTROLLER
#***************************************************************************

account:
    path:		/account
    defaults:	{ _controller: Ecommerce:Account:index }

account_addresses:
    path:		/account/addresses
    defaults:	{ _controller: Ecommerce:Account:Addresses }

account_create:
    path:		/account/create
    defaults:	{ _controller: Ecommerce:Account:create }

account_edit_address:
    path:		/account/edit/addresses/{address_id}
    defaults:	{ _controller: Ecommerce:Account:editAddress }

account_edit_details:
    path:		/account/edit/details
    defaults:	{ _controller: Ecommerce:Account:editDetails }

account_edit_email:
    path:		/account/edit/email
    defaults:	{ _controller: Ecommerce:Account:editEmail }

account_edit_password:
    path:		/account/edit/password
    defaults:	{ _controller: Ecommerce:Account:editPassword }

#***************************************************************************
# SECURITY CONTROLLER
#***************************************************************************

login:
    path:		/login
    defaults:	{ _controller: Ecommerce:Security:login }

login_check:
    path:		/login_check
    defaults:	{ _controller: Ecommerce:Security:loginCheck }

logout:
    path:		/logout
    defaults:	{ _controller: Ecommerce:Security:logout }
