app:
    resource: "@Ecommerce/Controller/"
    type:     annotation

#***************************************************************************
# INDEX CONTROLLER
#***************************************************************************

home:
    path:		/
    defaults:	{ _controller: Ecommerce:Index:index }

#***************************************************************************
# ACCOUNT CONTROLLER
#***************************************************************************

account:
    path:		/account
    defaults:	{ _controller: Ecommerce:Account:index }

account_addresses:
    path:		/account/addresses
    defaults:	{ _controller: Ecommerce:Account:Addresses }

account_create:
    path:		/account/create
    defaults:	{ _controller: Ecommerce:Account:create }

account_edit_details:
    path:		/account/edit/details
    defaults:	{ _controller: Ecommerce:Account:editDetails }

account_edit_email:
    path:		/account/edit/email
    defaults:	{ _controller: Ecommerce:Account:editEmail }

account_edit_password:
    path:		/account/edit/password
    defaults:	{ _controller: Ecommerce:Account:editPassword }

#***************************************************************************
# ADDRESS CONTROLLER
#***************************************************************************

address_create:
    path:		/address/create
    defaults:	{ _controller: Ecommerce:Address:create }

address_edit:
    path:		/address/edit/{address_id}
    defaults:	{ _controller: Ecommerce:Address:edit }

address_delete:
    path:		/address/delete
    defaults:	{ _controller: Ecommerce:Address:delete }

address_set_billing:
    path:		/address/set/billing
    defaults:	{ _controller: Ecommerce:Address:setBilling }

address_set_shipping:
    path:		/address/set/shipping
    defaults:	{ _controller: Ecommerce:Address:setShipping }

address_subdivisions:
    path:		/address/subdivisions
    defaults:	{ _controller: Ecommerce:Address:subdivisions }

address_locations:
    path:		/address/locations
    defaults:	{ _controller: Ecommerce:Address:locations }

#***************************************************************************
# SECURITY CONTROLLER
#***************************************************************************

login:
    path:		/login
    defaults:	{ _controller: Ecommerce:Security:login }

login_check:
    path:		/login_check
    defaults:	{ _controller: Ecommerce:Security:loginCheck }

logout:
    path:		/logout
    defaults:	{ _controller: Ecommerce:Security:logout }
