# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                memory: true

parameters:
    genders:
        f: Mme
        m: Mr
    knp_menu.renderer.twig.options:
        allow_safe_labels: true
        ancestorClass: active
        currentClass: active

services:
    Ecommerce.doctrine_subscriber.customer_address:
        class: Ecommerce\Doctrine\Subscriber\CustomerAddressSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Ecommerce.doctrine_subscriber.customer_address_details:
        class: Ecommerce\Doctrine\Subscriber\CustomerAddressDetailsSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Ecommerce.doctrine_subscriber.customer_details:
        class: Ecommerce\Doctrine\Subscriber\CustomerDetailsSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Ecommerce.form.type.address:
        class: Ecommerce\Form\Type\AddressType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: e_address }

    Ecommerce.form.type.gender:
        class: Ecommerce\Form\Type\GenderType
        arguments:
            - "%genders%"
        tags:
            - { name: form.type, alias: e_gender }

    Ecommerce.form.type.password:
        class: Ecommerce\Form\Type\PasswordType
        arguments:
        tags:
            - { name: form.type, alias: e_password }

    Ecommerce.locale_listener:
        class: Ecommerce\EventListener\LocaleListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    Ecommerce.menu_breadcrumb:
        class: Knp\Menu\MenuItem
        factory: ["@Ecommerce.menu_builder", createBreadcrumbsMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }

    Ecommerce.menu_builder:
        class: Ecommerce\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@translator"]

    Ecommerce.menu_main:
        class: Knp\Menu\MenuItem
        factory: ["@Ecommerce.menu_builder", createMainMenu]
        arguments: ["@request_stack", "@security.authorization_checker"]
        tags:
            - { name: knp_menu.menu, alias: main }

    Ecommerce.security_listener:
        class: Ecommerce\Listener\SecurityListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    Ecommerce.voter.request:
        class: Ecommerce\Menu\MenuVoter
        arguments: ["@service_container"]
        tags:
            - { name: knp_menu.voter }
